### ISSUE TITLE
Why is ctx->rni_count added twice in one occurrence？

### ISSUE THREAD

**Issue by iwishguo** [ARM-software/SCP-firmware#305]
https://github.com/ARM-software/SCP-firmware/blob/c5c09d704a02152d5ac61f2a21f6eafe61b86cd9/module/cmn_rhodes/src/mod_cmn_rhodes.c#L223

The above code seems strange. Is it dedicated to do so or a code bug?

Thanks,
Heyi

**Comment by CJKay** [comment]
@vijayenthiran-arm Could you take this? This seems to have been introduced with [a9ab01b](https://github.com/ARM-software/SCP-firmware/commit/a9ab01b6b5976cf65529fca43cd0354dea1f8624).

**Comment by vijayenthiran-arm** [comment]
Hi @iwishguo, incrementing rni_count inside the if condtion (ctx->rni_count++) is not required. I will soon post a fix for this. Thanks for pointing out.
