### ISSUE TITLE
PIK clock configs of RD-Daniel 

### ISSUE THREAD

**Issue by gvaumour** [ARM-software/SCP-firmware#342]
In ``product/rddaniel/scp_ram/config_pik_clock.c``, I see something that seems to be not consistent: 
````````
   [CLOCK_PIK_IDX_CLUS0_CPU0] = {
...
            .modulator_reg = &CLUSTER_PIK_PTR(0)->CORECLK[0].MOD,
...
    [CLOCK_PIK_IDX_CLUS1_CPU0] = {
...
            .modulator_reg = &CLUSTER_PIK_PTR(0)->CORECLK[0].MOD,
...
    [CLOCK_PIK_IDX_CLUS2_CPU0] = {
...
            .modulator_reg = &CLUSTER_PIK_PTR(2)->CORECLK[0].MOD,
````````
The ``modulator_reg`` of the Cluster 1 is pointing to ``CLUSTER_PIK_PTR(0)`` register , but for all the clocks the ``modulator_reg`` parameter points to ``CLUSTER_PIK_PTR(i)`` instead of 0 
Looks like a copy-paste error ? Not sure how much it does matter though 

Gregory V.

**Comment by CJKay** [comment]
Well observed!

@omasab Could you take a look at this? The XLR config also appears to exhibit this issue.

**Comment by omasab** [comment]
Thank you, will check about this.
