### ISSUE TITLE
n1sdp status

### ISSUE THREAD

**Issue by bukinr** [ARM-software/SCP-firmware#466]
I could not boot latest firmware on N1SDP machine.
The UEFI loader does not show up in the terminal.
Did any one test it ?

I only get this output:
```
0 dome:/home/br >sudo cu -f -l /dev/ttyUSB3 -s 115200
Connected.
[    0.000000]  ___  ___ ___      __ _
[    0.000000] / __|/ __| _ \___ / _(_)_ _ _ ____ __ ____ _ _ _ ___
[    0.000000] \__ | (__|  _|___|  _| | '_| '  \ V  V / _` | '_/ -_)
[    0.000000] |___/\___|_|     |_| |_|_| |_|_|_\_/\_/\__,_|_| \___|
[    0.000000]
[    0.000000] v2.8.0_2021-05-05_15-21-27-v2.8.0-27-g0f5795eb
[    0.000000]
[    0.000000] [FWK] Module initialization complete!
[    0.000000] [FIP] Invalid FIP ToC header name: [0x20040000]
[    0.000000] [FWK] Process event ([EVT 2:0]: [MOD 2] -> [MOD 2]) (-1)
```

**Comment by nicola-mazzucato-arm** [comment]
Hi @bukinr , thanks for bringing this up. We have recently updated the SCMI protocol in SCP therefore some other changes in the software stack have been required. In particular for UEFI, it may be the case that the relevant change has not yet been merged. This is the fix for it: https://edk2.groups.io/g/devel/message/74791
Would you be able to cherry-pick the change and re test?
Many thanks

**Comment by bukinr** [comment]
Yes, will check in a few minutes.

**Comment by bukinr** [comment]
@nicola-mazzucato-arm both patched and unpatched UEFI starts up on old SCP firmware (v2.5).
But on latest (v2.7) both of them do not start.

**Comment by bukinr** [comment]
- I don't know how to check Trusted Firmware version.
- I could not build SCP v2.6 or v2.7 due to this bug:
/home/br/dev/SCP-firmware/product/n1sdp/include/fmw_cmsis.h:32:10: fatal error: core_cm7.h: No such file or directory

**Comment by nicola-mazzucato-arm** [comment]
Hi @bukinr , which commands/instructions are you using to build the entire software stack?
You may be able to see the TF-A version in the logs.
The error you are seeing above is probably due to cmsis not initialised. Please run "git submodule update --init".

Thanks

**Comment by bukinr** [comment]
I used this instructions:
https://developer.arm.com/tools-and-software/open-source-software/firmware/edkii-uefi-firmware/building-edkii-uefi-firmware-for-arm-platforms

Although it does not say where to put new SCP binaries in N1SDP case.
Do I copy files correctly?
```
sudo cp ./build/product/n1sdp/mcp_romfw/release/bin/mcp_romfw.bin /mnt/SOFTWARE/mcp_rom.bin
sudo cp ./build/product/n1sdp/mcp_ramfw/release/bin/mcp_ramfw.bin /mnt/SOFTWARE/mcp_fw.bin
sudo cp ./build/product/n1sdp/scp_romfw/release/bin/scp_romfw.bin /mnt/SOFTWARE/scp_rom.bin
sudo cp ./build/product/n1sdp/scp_ramfw/release/bin/scp_ramfw.bin /mnt/SOFTWARE/scp_fw.bin
```

**Comment by bukinr** [comment]
Thanks, I was able to build and boot 2.7 firmware (not 2.8).
@nicola-mazzucato-arm Can you point me to the right instructions for the UEFI build, so I can update it as well?

**Comment by nicola-mazzucato-arm** [comment]
Those instructions should give you the full software stack and UEFI contains already a patch for it to be compatible with v2.8 of SCP-firmware. The "bitbake" process should do everything for you.

**Comment by bukinr** [comment]
I was able to build v2.8 of SCP-firmware but it does not boot:
```
NOTICE:  BL31: v2.4(debug):v2.4-451-g332649da4-dirty
NOTICE:  BL31: Built : 16:50:08, Mar 15 2021
INFO:    SDS: Detected SDS Memory Region (3520 bytes)
INFO:    GICv3 without legacy support detected.
INFO:    ARM GICv3 driver initialized in EL3
INFO:    Maximum SPI INTID supported: 991
INFO:    Initializing driver on Channel 0
WARNING: SCMI power domain protocol version 0x20000 incompatible with driver version 0x10000ERROR:   SCMI Initialization failed on channel 0
BACKTRACE: START: plat_arm_pwrc_setup
0: EL3: 0x4041d00
1: EL3: 0x404498c
2: EL3: 0x4041fc8
3: EL3: 0x4041e78
4: EL3: 0x4040118
BACKTRACE: END: plat_arm_pwrc_setup

**Comment by bukinr** [comment]
@nicola-mazzucato-arm is my tf-a version is good, otherwise how to replace tf-a?

**Comment by nicola-mazzucato-arm** [comment]
Hi @bukinr from the logs it looks like your TF-A is behind, so needs to be updated. If you follow the instructions for the arm-reference platforms, you can specify your own TF-A repo/path by using devtool:
`devtool modify trusted-firmware-a -n <your-tf-a-path>`
Then
`bitbake <recipe-component-name>` to rebuild everything again.

**Comment by bukinr** [comment]
Thanks @nicola-mazzucato-arm. I was able to update SCP firmware (including bl31 and uefi). I see that they are starting up fine.
But FreeBSD seem to stuck somewhere during boot after update. All kernel subsystems seem to have initialized propertly, but when it comes to userspace I see lots of instruction abort exceptions from EL0, so it never get booted with latest firmware.

**Comment by nicola-mazzucato-arm** [comment]
Hi @bukinr , would you be able to provide a bit more details? I am still not sure how you build all the pieces of f/w. Do you use yocto or do you manually build?

**Comment by nicola-mazzucato-arm** [comment]
Hi @bukinr any update on this? If you managed to solve this issue, can we close it?
Otherwise the following up-to-date instructions may give you a working starting point for N1SDP: https://gitlab.arm.com/arm-reference-solutions/arm-reference-solutions-docs/-/blob/master/docs/n1sdp/user-guide.rst
Thanks
