### ISSUE TITLE
Whether an RTOS is required after the multi-threading feature is removed

### ISSUE THREAD

**Issue by xia-s-xian** [ARM-software/SCP-firmware#598]
Hi:
    I understand that RTOS is only used if you are using multiple threads,but i find the scp remove the multi-threading feature, I am confused as to whether RTOS are still needed.

**Comment by tarek-arm** [comment]
Hi @xia-s-xian, RTOS is not required. You could run the firmware as bare-metal. It will be useful to understand your use case so we can help you more.
Thanks

**Comment by tarek-arm** [comment]
Question answered
