### ISSUE TITLE
gtimer timestamp is used by fwk log before it's initialized

### ISSUE THREAD

**Issue by cladstrife911** [ARM-software/SCP-firmware#614]
gtimer timestamp is used by fwk log before it's initialized resulting in the base address used to be 0x00000000.
Might be good to add some assertion in the mod_gtimer.

**Comment by tarek-arm** [comment]
Hi @cladstrife911 it is expected the timestamp will not be correct before initializing the gtimer module. Can you please elaborate on the assertion you would like to add? Maybe if you share a patch it will be helpful.
