### ISSUE TITLE
ELEM2_IDX invalid value

### ISSUE THREAD

**Issue by cladstrife911** [ARM-software/SCP-firmware#701]
https://github.com/ARM-software/SCP-firmware/blob/513ac076bd7775c2d0352d05ae211e0f2bac107b/framework/test/test_fwk_module.c#L20

Value should be 2?

**Comment by leandro-arm** [comment]
Hi @cladstrife911 
No, `ELEM2_IDX` is an element used in `FWK_MODULE_IDX_FAKE1` instead of `FWK_MODULE_IDX_FAKE0` where the others two elements are used.
Thanks,
Leandro
