### ISSUE TITLE
Unitary test and module in a sub directory

### ISSUE THREAD

**Issue by vingu-linaro** [ARM-software/SCP-firmware#757]
unitary test returns an error when trying to build unitary tests for modules/optee/smt. Looks like it doesn't support sub directory in modules.

$ make -f Makefile.cmake mod_test
CMake Error at module_common.cmake:20 (add_executable):
  The target name "mod_optee/mbx_unit_test" is reserved or not valid for
  certain CMake features, such as generator expressions, and may result in
  undefined behavior.
Call Stack (most recent call first):
  /home/vingu/Linaro/SCMI/SCP-firmware/module/optee/mbx/test/CMakeLists.txt:27 (include)

CMake Error at module_common.cmake:36 (target_compile_definitions):
  Cannot specify compile definitions for target "mod_optee/mbx_unit_test"
  which is not built by this project.
Call Stack (most recent call first):
  /home/vingu/Linaro/SCMI/SCP-firmware/module/optee/mbx/test/CMakeLists.txt:27 (include)

**Comment by mohamedasaker-arm** [comment]
This [draft PR](https://github.com/ARM-software/SCP-firmware/pull/804) shows how to create the unit test and the required modification.

**Comment by mohamedasaker-arm** [comment]
https://github.com/ARM-software/SCP-firmware/pull/804 is Merged and 
unblocks unitary tests for optee components 
https://github.com/ARM-software/SCP-firmware/pull/834
https://github.com/ARM-software/SCP-firmware/pull/806
https://github.com/ARM-software/SCP-firmware/pull/756
